name: Build
on: [push, pull_request]

jobs:
  build-linux:
    name: Linux
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Dependencies
      run: sudo apt install -y libasound2-dev pkg-config gcc g++
    - name: Build
      run: cargo build --release
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: ensemblecalc-linux
        path: target/release/ensemblecalc
  
  build-windows:
    name: Windows
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: ensemblecalc-windows
        path: target/release/ensemblecalc.exe